### ISSUE TITLE
improve flags as hex

### ISSUE THREAD

**Issue by marakew** [amarghosh/mp4viewer#12]
https://github.com/amarghosh/mp4viewer/blob/720f65c266618d48be8a18cbecad53cb23f62026/src/isobmff/fragment.py#L47

yield("Default sample flags", "0x%08x" %self.default_sample_flags)

https://github.com/amarghosh/mp4viewer/blob/720f65c266618d48be8a18cbecad53cb23f62026/src/isobmff/fragment.py#L89

yield('First sample flags', "0x%08x" %self.first_sample_flags)

**Comment by amarghosh** [comment]
Thanks for raising this. I am currently working on adding pylint checks to the repo, I will take care of these as part of that. If you need this fixed quicker, feel free to raise a PR.

**Comment by marakew** [comment]
I'm in no hurry

вт, 5 мар. 2024 г. в 14:23, Amarghosh Vadakkoot ***@***.***>:
