### ISSUE TITLE
imrove show desc of atom for console

### ISSUE THREAD

**Issue by marakew** [amarghosh/mp4viewer#13]
https://github.com/amarghosh/mp4viewer/blob/720f65c266618d48be8a18cbecad53cb23f62026/src/console.py#L20

```
     def show_node(self, node, prefix):
-        write("%s%s%s%s%s\n" %(prefix, self.header_prefix, ConsoleRenderer.COLOR_HEADER,
-            node.name, ConsoleRenderer.ENDCOL))
+        write("%s%s%s%s%s ***** (%s)\n" %(prefix, self.header_prefix, ConsoleRenderer.COLOR_HEADER,
+            node.name, ConsoleRenderer.ENDCOL, node.desc))
```

**Comment by amarghosh** [comment]
Planning to show the description using a separate colour when colour is enabled, and use parentheses or angle brackets otherwise.

**Comment by marakew** [comment]
iam analyze big mp4 files
output write at file for continue research
and try many variation of show description with many delimiters
seems my changes with () better
